apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notifications
  namespace: test-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Rajesh-Sangepu/youtube.git'
    path: argocd/notifications/manifests
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
